# This is a basic workflow to help you get started with Actions

name: Run Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on pull_request event
  pull_request:
    types: [opened]
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.results }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: API Endpoint Trigger
        id: step1
        uses: ./
        with:
          IAP_TOKEN: ${{secrets.IAP_TOKEN}}
          IAP_INSTANCE: ${{secrets.IAP_INSTANCE}}
          API_ENDPOINT: ${{secrets.API_ENDPOINT}}
          API_ENDPOINT_BODY: ${{secrets.API_ENDPOINT_BODY}}
          TIME_INTERVAL: 15
          NO_OF_ATTEMPTS: 10
          JOB_STATUS: 1
      - name: Get output
        run: echo "${{steps.step1.outputs.results}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.output1}}"
