# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'abc'
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.results }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: API Endpoint Trigger
        id: step1
        uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IAP_TOKEN: ${{secrets.IAP_TOKEN}}
          IAP_INSTANCE: ${{secrets.IAP_INSTANCE}}
          TIMEOUT: 15
          NO_OF_ATTEMPTS: 10
          API_ENDPOINT: ${{secrets.API_ENDPOINT}}
          API_ENDPOINT_BODY: ${{secrets.API_ENDPOINT_BODY}}
          JOB_STATUS: 1
      - name: Get output
        run: echo "${{steps.step1.outputs.results}}"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.output1}}"
